set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property BITSTREAM.CONFIG.CONFIGRATE 33 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]

create_clock -name CLK -period 10 [get_ports CLK]
create_generated_clock -name CLKDIV -source [get_ports CLK] -divide_by 256 [get_pins SYSCOM_I/r_clk_div_reg[7]/Q]

set_property PACKAGE_PIN V17  [get_ports RESET]
set_property PACKAGE_PIN W5   [get_ports CLK]
set_property PACKAGE_PIN T18  [get_ports {BTNU}]
set_property PACKAGE_PIN W19  [get_ports {BTNL}]
set_property PACKAGE_PIN U18  [get_ports {BTNC}]
set_property PACKAGE_PIN T17  [get_ports {BTNR}]
set_property PACKAGE_PIN U17  [get_ports {BTND}]
set_property PACKAGE_PIN R2   [get_ports SW1]
set_property PACKAGE_PIN T1   [get_ports SW2]
set_property PACKAGE_PIN U1   [get_ports SW3]
set_property PACKAGE_PIN W4   [get_ports {SEG[11]}]
set_property PACKAGE_PIN V4   [get_ports {SEG[10]}]
set_property PACKAGE_PIN U4   [get_ports {SEG[9]}]
set_property PACKAGE_PIN U2   [get_ports {SEG[8]}]
set_property PACKAGE_PIN V7   [get_ports {SEG[7]}]
set_property PACKAGE_PIN U7   [get_ports {SEG[6]}]
set_property PACKAGE_PIN V5   [get_ports {SEG[5]}]
set_property PACKAGE_PIN U5   [get_ports {SEG[4]}]
set_property PACKAGE_PIN V8   [get_ports {SEG[3]}]
set_property PACKAGE_PIN U8   [get_ports {SEG[2]}]
set_property PACKAGE_PIN W6   [get_ports {SEG[1]}]
set_property PACKAGE_PIN W7   [get_ports {SEG[0]}]
set_property PACKAGE_PIN L1  [get_ports {LED[15]}]
set_property PACKAGE_PIN P1  [get_ports {LED[14]}]
set_property PACKAGE_PIN N3  [get_ports {LED[13]}]
set_property PACKAGE_PIN P3  [get_ports {LED[12]}]
set_property PACKAGE_PIN U3  [get_ports {LED[11]}]
set_property PACKAGE_PIN W3  [get_ports {LED[10]}]
set_property PACKAGE_PIN V3  [get_ports {LED[9]}]
set_property PACKAGE_PIN V13 [get_ports {LED[8]}]
set_property PACKAGE_PIN V14 [get_ports {LED[7]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]
set_property PACKAGE_PIN U15 [get_ports {LED[5]}]
set_property PACKAGE_PIN W18 [get_ports {LED[4]}]
set_property PACKAGE_PIN V19 [get_ports {LED[3]}]
set_property PACKAGE_PIN U19 [get_ports {LED[2]}]
set_property PACKAGE_PIN E19 [get_ports {LED[1]}]
set_property PACKAGE_PIN U16 [get_ports {LED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports {BTNU}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTNL}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTNC}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTNR}]
set_property IOSTANDARD LVCMOS33 [get_ports {BTND}]
set_property IOSTANDARD LVCMOS33 [get_ports SW1]
set_property IOSTANDARD LVCMOS33 [get_ports SW2]
set_property IOSTANDARD LVCMOS33 [get_ports SW3]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SEG[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
